# Generated by Django 4.1.7 on 2024-04-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMeida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="addressdetails",
            old_name="latitude",
            new_name="line1",
        ),
        migrations.RenameField(
            model_name="addressdetails",
            old_name="longtitude",
            new_name="line2",
        ),
        migrations.RemoveField(
            model_name="city",
            name="ward_id",
        ),
        migrations.AddField(
            model_name="ward",
            name="city_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ward_city",
                to="app.city",
            ),
        ),
    ]
